version: '3.8'

services:
  # Combined agent + backend service
  app:
    build: 
      context: .
      dockerfile: Dockerfile.combined
    ports:
      - "8000:8000"  # Backend port
      - "2024:2024"  # Agent port
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - LANGGRAPH_SERVER_URL=http://localhost:2024
      - FRONTEND_URL=${FRONTEND_URL}
    volumes:
      - app_data:/app/data

  web:
    build: ./web
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
    depends_on:
      - app

volumes:
  app_data: